name: Build and Release

on:
  push:
    branches:
      - main  # Set to your main branch

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'  # Set this to your Go version

    - name: Build the application
      run: make build

    - name: Install dbmate
      run: |
        curl -L https://github.com/amacneil/dbmate/releases/download/v1.11.0/dbmate-linux-amd64 -o dbmate
        chmod +x dbmate
        sudo mv dbmate /usr/local/bin/

    - name: Run database migrations
      run: make migrateup

    - name: Run the application
      run: make run

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: database-file
        path: quran.db

    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "Release ${{ github.ref }}"

    - name: Upload Release Asset
      uses:  softprops/action-gh-release@v2
      with:
        files: quran.db
        token: ${{ secrets.GITHUB_TOKEN }}
        release: ${{ github.ref }}
        asset_name: quran.db
        content_type: application/octet-stream