name: Main

on: push

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'  # Set this to your Go version

    - name: Build the application
      run: make build

    - name: Install dbmate
      run: |
        curl -L https://github.com/amacneil/dbmate/releases/download/v1.11.0/dbmate-linux-amd64 -o dbmate
        chmod +x dbmate
        sudo mv dbmate /usr/local/bin/

    - name: Run database migrations
      run: make migrateup

    - name: Run the application
      run: make run

    - name: Create and Upload Release Asset
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          quran.db
          ./bin/main
        token: ${{ secrets.GITHUB_TOKEN }}