name: Release Assets Workflow

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'  # Set this to your Go version
      - name: Build project
        run: make build
      - name: Install dbmate
        run: |
          curl -L https://github.com/amacneil/dbmate/releases/download/v1.11.0/dbmate-linux-amd64 -o dbmate
          chmod +x dbmate
          sudo mv dbmate /usr/local/bin/

      - name: Run database migrations
        run: make migrateup

      - name: Run the application
        run: make run

      - name: Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./bin/*
            quran.db
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
